micronaut:
  application:
    name: kafkaBase
kafka.bootstrap.servers: localhost:9092

kafka:
  enabled: true
  consumers:
    enabled: true
  producers:
    enabled: true

service:
  kafka:
    topics:
      product-created: "product.created"

jackson:
  date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
